from phoneNumber import *
print("--"*24)
print("Testing phone number from 201 area code (NJ)")
a=Phone_Number("201-555-0100")
a.printPhoneNumber()
a.checkAreaCode()
print("-~"*24)
print("\nTesting phone number from 981 area code (not used (yet))")
b=Phone_Number("981-555-0100")
b.printPhoneNumber()
b.checkAreaCode()
print("\nTesting phone number from 760")
c=Phone_Number("760-555-0102")
c.printPhoneNumber()
c.checkAreaCode()
print("\nTESTING creating a \"random\" fictional number")
print("TESTING returning as a string\n")
d=Phone_Number()
d=d.createFictionalPhoneNumber()
print("Phone Number: {}\n".format(d))
print("\nTESTING checking the area code of above phone number")
d.checkAreaCode()
